### ISSUE TITLE
Odd line number output behavior from 'MismatchedBracketCheck' rule

### ISSUE THREAD

**Issue by mschuchard** [willthames/ansible-lint#118]
Executing ansible-lint 2.3.8 on example.yml in the examples directory yields:

```
[ANSIBLE0003] mismatched braces
example.yml:2
debug oops a missing {{bracket}
```

Which is many lines above the actual infraction.

Interestingly enough, you can edit the example.yml to discover that the check always returns the line number of the final top-level item.

examples -

```
---
- hosts: webservers







  vars:
    oldskool: "1.2.3"
    bracket: "and close bracket"

  tasks:
  - name: bobbins
    action: command echo ${oldskool}

  - name: blah
    action: debug oops a missing {{bracket}
```

returns line 2

```
---
- hosts: webservers

  - name: blah
    action: debug oops a missing {{bracket}
```

returns line 2

```
---
- hosts: webservers
- foo: foo
- bar: bar
- baz: baz

  - name: blah
    action: debug oops a missing {{bracket}
```

returns line 5

I am unsure what part of the code causes this error, but I have verified the line number returned for this rule is always the final top level item.  This can be verfieid by editing the example.yml in this repository in a similar fashion as the above examples.
