### ISSUE TITLE
ansible-lint does not sanitize its output, printing unicode strings is not reliable.

### ISSUE THREAD

**Issue by do3cc** [willthames/ansible-lint#140]
# Issue Type
- Bug report

# How to get there:
Create a file
test.yml
```
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
     my_name: a_b_cö   
```
Notice the excessive whitespace of the last line.

# Desired Behaviour

I execute ansible lint and get a warning

# Actual Behaviour (Bug report only)
I get a traceback:
Traceback (most recent call last):
  File "./bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./bin/ansible-lint", line 106, in main
    print(formatter.format(match))
  File "/private/tmp/bla/bla2/lib/python2.7/site-packages/ansiblelint/formatters/__init__.py", line 9, in format
    match.line)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 19: ordinal not in range(128)
