### ISSUE TITLE
False positive EANSIBLE0013 when using globs

### ISSUE THREAD

**Issue by allanlewis** [willthames/ansible-lint#163]
# Issue Type
- Bug report

# Ansible and Ansible Lint details
```
ansible --version
2.1.0.0
ansible-lint --version
3.0.1
```
- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour
`EANSIBLE0013` should not be raised for `shell` tasks that use globs.

# Actual Behaviour
`EANSIBLE0013` is raised for this task:
```yaml
    - name: Deploy ssh key for root
      shell: rsync /home/foo/.ssh/id_rsa* /root/.ssh/
      args:
        creates: /root/.ssh/id_rsa
```
Output of `ansible-lint`:
```
[ANSIBLE0013] Use shell only when shell functionality is required
<path>.yml:<n>
Task/Handler: Deploy ssh key for root
```
