### ISSUE TITLE
Enforce pure YAML syntax

### ISSUE THREAD

**Issue by AMeng** [willthames/ansible-lint#164]
# Feature request

# Desired Behavior

Add a rule to enforce pure YAML. There are a number of benefits to this (linked below). The rule would disallow the use of `key=value` in a task. For example, instead of writing a `mount` directive like this:

```yaml
---
- name: Ensure the floppy disk is mounted.
  mount: "name=/mnt/floppy src=/dev/fd0 fstype=fuse opts=allow_other,user=nobody,nonempty dump=0 passno=0 state=mounted"
```

It should be written like this:

```yaml
---
- name: Ensure the floppy disk is mounted.
  mount:
    name: /mnt/floppy
    src: /dev/fd0
    fstype: fuse
    opts: "allow_other,user=nobody,nonempty"
    dump: 0
    passno: 0
    state: mounted
```

This could certainly be off by default, but in my opinion all Ansible roles should be written this way. Here are some useful links justifying this choice:

 * [Why you should use YAML as YAML with Ansible](http://blog.bandwidth.com/why-you-should-use-yaml-as-yaml-with-ansible/)
 * [OpenShift Ansible Best Practices](https://github.com/openshift/openshift-ansible/blob/master/docs/best_practices_guide.adoc#Ansible-files-SHOULD-NOT-use-JSON-use-pure-YAML-instead)
 * [YAML Best Practices for Ansible Playbooks](http://www.jeffgeerling.com/blog/yaml-best-practices-ansible-playbooks-tasks)
