### ISSUE TITLE
ansible-lint exits when using newer role dependency dict structure

### ISSUE THREAD

**Issue by sjmiller** [willthames/ansible-lint#174]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version: 2.1.0.0
ansible-lint --version: 3.1.2
```

- ansible installation method: homebrew
- ansible-lint installation method: pip

# Desired Behaviour

Command should not exit with error when role dependency is in newer dictionary format

# Actual Behaviour (Bug report only)

When a role dependency in `meta/main.yml` is defined like so:
```
dependencies:
  - name: my-role
    src: https://example.com/my-role.git
    scm: git
```
Errors with with:
`role dict {u'src': u'https://example.com/my-role.git', u'name': u'my-role', u'scm': u'git'} does not contain a "role" key`

Defining a role dependency providing the rolespec format in the `role` key appears to be deprecated in ansible 2.1.0.0.
