### ISSUE TITLE
UsingBareVariablesIsDeprecatedRule bug with dictionary default

### ISSUE THREAD

**Issue by jzafran** [willthames/ansible-lint#190]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible-lint --version
```
Ansible 1.9
Ansible-lint 3.2.5 (and on master branch)

- ansible installation method: pip
- ansible-lint installation method: pip

# Task
UsingBareVariablesIsDeprecatedRule raises an error when a task has `with_items` with a default empty dictionary:  
```yml
- name: configure
  ini_file:
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ ini_options | default({}) }}"
```

# Desired Behaviour
This should not be considered an error; the syntax is ok for Ansible 1.9 and 2+.

# Actual Behaviour (Bug report only)

> [ANSIBLE0015] Found a bare variable '{{ ini_options | default({}) }}' used in a 'with_dict' loop. You should use the full variable syntax ('{{{{ ini_options | default({}) }}}}')

I have a fix, and will put up a PR soon for this.
