### ISSUE TITLE
4 digit octal permissions, instead of 4-5 digit with leading zero

### ISSUE THREAD

**Issue by charims** [willthames/ansible-lint#266]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

ansible-lint --version
ansible-lint 3.4.12
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Desired Behaviour

Rule "[ANSIBLE0009] Octal file permissions must contain leading zero" is incorrect
instead of ensuring a leading zero, it should ensure that mode octal permissions are 4 digits in length with values ranging 0-7.

Suggested regex:
```
valid_mode_regex = re.compile(r'^\s+mode:\s*[0-7]{4}\s*$')
```
# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Please note there was a similiar bug report at https://github.com/willthames/ansible-lint/issues/109
That issue was resolved by using the following regex:
```
valid_mode_regex = re.compile(r'^\s+mode:\s*0[0-7]{3,4}\s*$')
```
However, this forces a leading zero, as such, 02755 would pass this test, but is an invalid mode for a file. Chmod seems to accept it anyways, and strips the leading zero. The ansible file module however, does not accept it and fails.

with:
- playbook
```
---
- name: Test
  hosts: all
  tasks:
  - name: Ensure perms on journal
    file:
      path: /var/log/journal
      state: directory
      owner: root
      group: root
      mode: 2755
```

- output of running ansible-lint
```
[ANSIBLE0009] Octal file permissions must contain leading zero
test.yml:5
Task/Handler: Ensure perms on journal
```

- Failing Playbook (but passes linter)
```
---
- name: Test
  hosts: all
  tasks:
  - name: Ensure perms on journal
    file:
      path: /var/log/journal
      state: directory
      owner: root
      group: root
      mode: 02755
```
- output of running ansible-lint
```
Nothing
```
