### ISSUE TITLE
throw error for use of lists as params to when, changed_when, failed_when

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#274]
It seems to be an extremely common error to a list as parameter for `when:`, `changed_when:` and `failed_when:`.

Ansible accepts it but the behaviour is not documenter or consistent. Just try to google for it and you will probably get more confused after reading the threads.

It is unclear which would happen:
- non empty list is evaluated as true, ignoring conditions
- AND would be applied between conditions
- OR would be applied between conditions

Example:
```
   - name: test
      shell: false
      when:
        - false
        - false
      
```
