### ISSUE TITLE
Included tasks via include_tasks or import_tasks will not be checked

### ISSUE THREAD

**Issue by MatrixCrawler** [willthames/ansible-lint#285]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.4.1.0 (stable-2.4 adc3bedaa2) last updated 2017/09/29 11:28:30 (GMT +200)
ansible-lint 3.4.15
```

- ansible installation method: source
- ansible-lint installation method: pip

# Desired Behaviour

If i iclude a subtask with import_tasks or include_tasks i expect that ansible-lint would check those files.

# Actual Behaviour (Bug report only)

When i am using the _include_tasks_ or _import_tasks_ directive instead of _include_, ansible-lint will not check the included tasks.
Here is my main.yml that is working, but deprecated sind ansible 2.4
```
- name: Deploying configuration maps
  include: configuration-maps.yml
  with_items:
    - { name: someItem.yml }
  loop_control:
    loop_var: configuration_value
```

This version will not include the configuration-maps.yml
```
- name: Deploying configuration maps
  include_tasks: configuration-maps.yml
  with_items:
    - { name: someItem.yml }
  loop_control:
    loop_var: configuration_value
```
