### ISSUE TITLE
Tags for blocks

### ISSUE THREAD

**Issue by nmulvihill** [willthames/ansible-lint#288]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version 
   2.3.1.0
ansible-lint --version
   3.4.12
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour
Using the example TaskHasTag rule, I would expect that if a task is inside a block and the block is tagged, the task does not have to be. 
```
- block:
   - name: task
      win_something:
         args: XXX
   - name: another task
      win_something
         args2: XXX

   tags: [tags,for,both,tasks]
```

# Actual Behaviour (Bug report only)
Reports an error.

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve)
with:
- playbook
  See above example.
- output of running ansible-lint
   *Task must have a tag*
